# Yaml configuration file definition for git hub actions
name: TEST
on: push

jobs:
    test_project:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2 
            - run: 
                python -m pip install --upgrade pip
                pip3 install -r requirements.txt
                python manage.py test