# Generated by Django 5.1.4 on 2025-02-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('gmail', models.EmailField(max_length=255, unique=True)),
                ('flights', models.ManyToManyField(blank=True, related_name='passangers', to='users.flight')),
            ],
        ),
        migrations.DeleteModel(
            name='Passanger',
        ),
    ]
