# Generated by Django 5.2 on 2025-04-21 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_passenger_first_name_remove_passenger_flights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='capacity',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
