# Generated by Django 5.2 on 2025-04-24 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_flight_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.passenger'),
        ),
    ]
