services:
  db: 
    # Postgres predefined image
    image: postgres
    environment:
      - POSTGRES_PASSWORD=@Harmon|Health2024
    volumes:
      - postgres_data:/var/lib/postgresql/data  
  web:
    # Using our dockerfile
    build: .
    # Connecting my development machine to the container
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
