services:
  db: 
    # Postgres predefined image
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=@HarmonHealth
      - POSTGRES_USER=peter_coder    
      - POSTGRES_DB=Airport_database
    volumes:
      - postgres_data:/var/lib/postgresql/data  
  web:
    # Using our dockerfile
    build: .
    # Connecting my development machine to the container
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
