# Yaml configuration file definition for git hub actions
name: TEST

on:
  push:
    branches:
      - main

jobs:
  test_project:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r airport_app/requirements.txt

      - name: Run tests
        run: python airport_app/manage.py test
